### ISSUE TITLE
Gulp problem 

### ISSUE THREAD

**Issue by Karuma** [subodha/magento-2-gulp#3]
Hi 
I have some problems with this gulp and magenta 2.2.2
When i type gulp i get:  
![2018-01-10 5 _li](https://user-images.githubusercontent.com/4147997/34793901-37749730-f64d-11e7-832f-cafb22d07124.jpg)

**Comment by subodha** [comment]
Hi @Karuma ,

I have not tested this on magento 2.2.2 seems they have changed some configaration. I'll check and let you know

Thanks

**Comment by DnD-Foster** [comment]
Hi @Karuma ,

To solve this problem on magento 2.2.2, I had to redefine filesRouter et set the alias like this : 

<img width="581" alt="capture d ecran 2018-01-11 a 17 50 11" src="https://user-images.githubusercontent.com/32138314/34836355-ffbc7942-f6f7-11e7-9169-8bf42270de2d.png">

I hope it will work for you

**Comment by Webmasterei** [comment]
@antoine-fontaine Thanks for your solution. Did you do this under line 50? Could you provide a PR for that? I put it there, but it does not work.

**Comment by subodha** [comment]
hi @Karuma  and @Webmasterei  please change the code like below
![image](https://user-images.githubusercontent.com/4123435/35673358-5b065adc-0767-11e8-8837-1168e88df044.png)

Hope this will help you guys. If you have any issue please let me know
