### ISSUE TITLE
LESS compile time

### ISSUE THREAD

**Issue by mattkrupnik** [subodha/magento-2-gulp#4]
Hi,
what is your LESS compile time? My every change get around 7-10s :( Do you have any idea how to minimize it?

**Comment by subodha** [comment]
Hi @mattkrupnik ,

Your time is the normal time. normaly it get 20s when we use Grunt.
Anyway I'll check wether we have any posible to raduse this time more.

Currently I'm working on some changes and it will save initial setup time of the theme.
